# This is a basic workflow to help you get started with Actions

name: Greeting from CHENG Chi Yin

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: CY
          LAST_NAME: Cheng
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME
